version: '3.8'
services:
  experiment-producer:
    image: dclandau/cec-experiment-producer
    command: 
      - "--secret-key" 
      - "${SECRET_KEY}"
      - "--brokers"
      - "${BROKERS}"
      - "--topic"
      - "${TOPIC}"
      - "--topic-document"
      - "${TOPIC_DOCUMENT}"
      - "--config-file"
      - "config.json"
    ports:
      - '3001:3001'
    extra_hosts: 
      - host.docker.internal:host-gateway
    environment: 
      - SERVICE_ENVIRONMENT=${SERVICE_ENVIRONMENT}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: 5
    volumes:
      - ./experiment-producer/auth:/experiment-producer/auth
      - ./experiment-producer/.env:/experiment-producer/.env
      - ./experiment-producer/config.json:/config.json

  notifications-service:
    image: dclandau/cec-notifications-service
    command: 
      - "--secret-key" 
      - "${SECRET_KEY}"
      - "--external-ip"
      - "${NOTIFICATIONS_EXTERNAL_IP}"
    ports:
      - "3000:3000"
    extra_hosts: 
      - host.docker.internal:host-gateway
    environment: 
      - SERVICE_ENVIRONMENT=${SERVICE_ENVIRONMENT}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: 5
    volumes:
      - ./notifications-service/.env:/notifications-service/.env

  http-load-generator:
    image: dclandau/cec-http-load-generator
    ports:
      - "3002:3002"
    command: 
      - --brokers 
      - "${BROKERS}"
      - --topic 
      - ${TOPIC_DOCUMENT}
      - --group-id 
      - "${HTTP_CONSUMER_GROUP}"
      - --consumer-wait-before-send 
      - "${HTTP_CONSUMER_WAIT_BEFORE_SEND}"
      - --hosts-file
      - hosts.json
      - --min-batch-size
      - "${HTTP_MIN_BATCH_SIZE}"
      - --max-batch-size
      - "${HTTP_MAX_BATCH_SIZE}"
      - --num-generations
      - "${HTTP_NUM_GENERATIONS}" 
      - --requestor-lag 
      - "5" 
      - --requestor-retries
      - "${HTTP_RETRIES}" 
      - --requestor-max-in-flight
      - "${HTTP_MAX_IN_FLIGHT}" 
      - --stable-rate-duration
      - "60"
    extra_hosts: 
      - host.docker.internal:host-gateway
    environment: 
      - SERVICE_ENVIRONMENT=${SERVICE_ENVIRONMENT}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: 5
    volumes:
      - ./auth:/app/auth
      - ./http-load-generator/hosts.json:/app/hosts.json
