[package]
name = "notifications-service"
version = "0.1.0"
edition = "2021"
default-run = "notifications-service"

[[bin]]
name = "generate-jwt-token"
path = "src/generate_token.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poem-openapi = { version = "5.1.16", features = ["swagger-ui"]}
poem = { version = "3.1.12", features = ["test"] }
tokio = { version = "1", features = ["full"]}
serde = "1.0.183"
serde_json = "1.0.104"
tracing-subscriber = "0.3.17"
tracing = "0.1"
clap = { version = "4", features = ["derive", "cargo"]}
rand = "0.8.2"
generic-array = "0.14.7"
aes-gcm = "0.10.2"
base64 = "0.21.2"
jsonwebtoken = "8.3.0"
sqlx = { version = "0.7", features = [ "runtime-tokio", "postgres" ] }
dotenv = "0.15.0"
prometheus-client = "0.21.2"

event-hash = { path = "../event-hash" }
